-- CreateTable
CREATE TABLE "Museum" (
    "id" TEXT NOT NULL,
    "landuse" TEXT,
    "name" TEXT,
    "tourism" TEXT,
    "museum" TEXT,
    "museum_type" TEXT,
    "alt_name" TEXT,
    "description" TEXT,
    "architect" TEXT,
    "start_date" TEXT,
    "old_name" TEXT,
    "note" TEXT,
    "operator" TEXT,
    "operator_name" TEXT,
    "ref:isil" TEXT,
    "building" TEXT,
    "building:levels" TEXT,
    "level" TEXT,
    "roof:shape" TEXT,
    "roof_levels" TEXT,
    "height" TEXT,
    "addr:city" TEXT,
    "addr:country" TEXT,
    "addr:housenumber" TEXT,
    "addr:postcode" TEXT,
    "addr:street" TEXT,
    "addr:suburb" TEXT,
    "phone" TEXT,
    "railway" TEXT,
    "phone:mobile" TEXT,
    "contact:website" TEXT,
    "email" TEXT,
    "fax" TEXT,
    "website" TEXT,
    "wikipedia" TEXT,
    "wikidata" TEXT,
    "wheelchair" TEXT,
    "toilets" TEXT,
    "toilets:access" TEXT,
    "toilets:wheelchair" TEXT,
    "changing_table" TEXT,
    "fee" TEXT,
    "opening_hours" TEXT,
    "opening_hours:signed" TEXT NOT NULL,
    "check_date" TEXT,
    "check_date:opening_hours" TEXT,
    "@geometry" TEXT,
    "geometry" JSONB,
    "historic" TEXT,
    "tourism_1" TEXT,

    CONSTRAINT "Museum_pkey" PRIMARY KEY ("id")
);
